name: Port GitHub Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

# Grant the GITHUB_TOKEN the right scopes to checkout code and pull GHCR images
permissions:
  contents: read
  packages: read

jobs:
  sync-github:
    name: Sync GitHub Repos & PRs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read      # for any checkout steps
      packages: read      # to pull from ghcr.io

    steps:
      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GitHub Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: github
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.getport.io"
          config: |
            github_token: ${{ secrets.GH_PAT }}     # or ${{ secrets.GITHUB_TOKEN }}
            repositories:
              - "danielsovo/test-project-port"
